name: Docker

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync BaPs
        uses: actions/checkout@v3
        with:
          repository: gucooing/BaPs
          ref: "main"
          lfs: true
          fetch-depth: 0

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: github docker login
        run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u gucooing --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            excel_url=${{ secrets.EXCEL_URL }}
            sha=${{ env.SHA }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/gucooing/baps:latest